package org.researchedc.domain.user;
// default package
// Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.researchedc.domain.DataMapDomainObject;
import org.researchedc.domain.Status;
import org.researchedc.domain.datamap.Item;
import org.researchedc.domain.datamap.ItemGroup;
import org.researchedc.domain.datamap.Study;
import org.researchedc.domain.datamap.StudyUserRole;
import org.researchedc.domain.technicaladmin.AuditUserLoginBean;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;


/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "user_account", schema = "public")
@GenericGenerator(name = "id-generator", strategy = "native", parameters = { @Parameter(name = "sequence", value = "user_account_user_id_seq") })

public class UserAccount extends DataMapDomainObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private UserAccount userAccount;
	private UserType userType;
	private Status status;
	private String userName;
	private String passwd;
	private String firstName;
	private String lastName;
	private String email = "";
	private Study activeStudy;
	private String institutionalAffiliation;
	private Date dateCreated;
	private Date dateUpdated;
	private Date dateLastvisit;
	private Date passwdTimestamp;
	private String passwdChallengeQuestion;
	private String passwdChallengeAnswer;
	private String phone;
	private Integer updateId;
	private boolean enabled;
	private boolean accountNonLocked;
	private int lockCounter;
	private boolean runWebservices;
	private String accessCode;
	private String timeZone;
	private boolean enableApiKey;
	private String apiKey;
	
	private List<Item> items;
	private List<ItemGroup> itemGroups;
	private List<StudyUserRole> studyUserRoles ;
	private Integer version;

	public UserAccount() {
	}

	public UserAccount(int userId, boolean enabled, boolean accountNonLocked,
			int lockCounter, boolean runWebservices) {
		this.userId = userId;
		this.enabled = enabled;
		this.accountNonLocked = accountNonLocked;
		this.lockCounter = lockCounter;
		this.runWebservices = runWebservices;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
    @GeneratedValue(generator = "id-generator")
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id")
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_type_id")
	public UserType getUserType() {
		return this.userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}

	 @Type(value = org.researchedc.domain.enumsupport.CodedEnumType.class, parameters = @org.hibernate.annotations.Parameter(name = "enumClassname", value = "org.researchedc.bean.core.Status"))
	  @Column(name = "status_id")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "user_name", length = 64)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "passwd")
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "first_name", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 120)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = "";
	}

	
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "active_study")
	public Study getActiveStudy() {
		return this.activeStudy;
	}

	public void setActiveStudy(Study activeStudy) {
		this.activeStudy = activeStudy;
	}

	@Column(name = "institutional_affiliation")
	public String getInstitutionalAffiliation() {
		return this.institutionalAffiliation;
	}

	public void setInstitutionalAffiliation(String institutionalAffiliation) {
		this.institutionalAffiliation = institutionalAffiliation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", length = 4)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_updated", length = 4)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_lastvisit", length = 8)
	public Date getDateLastvisit() {
		return this.dateLastvisit;
	}

	public void setDateLastvisit(Date dateLastvisit) {
		this.dateLastvisit = dateLastvisit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "passwd_timestamp", length = 4)
	public Date getPasswdTimestamp() {
		return this.passwdTimestamp;
	}

	public void setPasswdTimestamp(Date passwdTimestamp) {
		this.passwdTimestamp = passwdTimestamp;
	}

	@Column(name = "passwd_challenge_question", length = 64)
	public String getPasswdChallengeQuestion() {
		return this.passwdChallengeQuestion;
	}

	public void setPasswdChallengeQuestion(String passwdChallengeQuestion) {
		this.passwdChallengeQuestion = passwdChallengeQuestion;
	}

	@Column(name = "passwd_challenge_answer")
	public String getPasswdChallengeAnswer() {
		return this.passwdChallengeAnswer;
	}

	public void setPasswdChallengeAnswer(String passwdChallengeAnswer) {
		this.passwdChallengeAnswer = passwdChallengeAnswer;
	}

	@Column(name = "phone", length = 64)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "update_id")
	public Integer getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Integer updateId) {
		this.updateId = updateId;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public void setAccountNonLocked(boolean accountNonLocked) {
		this.accountNonLocked = accountNonLocked;
	}

	@Column(name = "lock_counter", nullable = false)
	public int getLockCounter() {
		return this.lockCounter;
	}

	public void setLockCounter(int lockCounter) {
		this.lockCounter = lockCounter;
	}

	public void setRunWebservices(boolean runWebservices) {
		this.runWebservices = runWebservices;
	}
	
	
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public List getUserRoleAccesses() {
		return this.userRoleAccesses;
	}

	public void setUserRoleAccesses(List userRoleAccesses) {
		this.userRoleAccesses = userRoleAccesses;
	}*/

    @Column(name = "access_code", length = 64)
	public String getAccessCode() {
        return accessCode;
    }

    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }

    @Column(name = "time_zone", length = 255)
    public String getTimeZone() {
        return timeZone;
    }

    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    public void setEnableApiKey(boolean enableApiKey) {
        this.enableApiKey = enableApiKey;
    }

    @Column(name = "api_key", length = 255)
    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public List<Item> getItems() {
		return this.items;
	}

	public void setItems(List<Item> items) {
		this.items = items;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public List<ItemGroup> getItemGroups() {
		return this.itemGroups;
	}

	public void setItemGroups(List<ItemGroup> itemGroups) {
		this.itemGroups = itemGroups;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public List<StudyUserRole> getStudyUserRoles() {
		return this.studyUserRoles;
	}

	public void setStudyUserRoles(List<StudyUserRole> studyUserRoles) {
		this.studyUserRoles = studyUserRoles;
	}*/


}
