dbType=postgres
dbHost=postgres
dbPort=5432
db=researchedc
dbUser=researchedc
dbPass=researchedc
filePath=/app/data/
log.dir=/app/logs
logLocation=local
logLevel=info
sysURL=http://localhost:8080/app/
maxInactiveInterval=3600
ldap.enabled=false
hibernate.ddl.auto=none
extract.number=99
collectStats=false
designerURL=
OpenClinica.version=0.1
