dbType=postgres
dbHost=localhost
dbPort=5433
db=researchedc
dbUser=researchedc
dbPass=researchedc
filePath=/home/openclinica/ResearchEDC/data/
log.dir=/home/openclinica/ResearchEDC/logs
logLocation=local
logLevel=info
sysURL=http://172.16.0.9:80/MainMenu
maxInactiveInterval=3600
ldap.enabled=false
ldap.host=ldap://localhost:389
ldap.userDn=
ldap.password=
ldap.loginQuery=(sAMAccountName={0})
ldap.passwordRecoveryURL=
ldap.userSearch.baseDn=
ldap.userSearch.query=
ldap.userData.distinguishedName=distinguishedName
ldap.userData.username=sAMAccountName
ldap.userData.firstName=givenName
ldap.userData.lastName=sn
ldap.userData.email=mail
ldap.userData.organization=company
org.quartz.jobStore.misfireThreshold=18000000
org.quartz.threadPool.threadCount=1
org.quartz.threadPool.threadPriority=5
hibernate.ddl.auto=none
extract.number=99
collectStats=false
designerURL=https://designer13.openclinica.com/
OpenClinica.version=0.1
