dbType=postgres
dbHost=localhost
dbPort=5432
db=researchedc
dbUser=researchedc
dbPass=researchedc
filePath=./data
log.dir=./logs
logLocation=local
logLevel=info
sysURL=http://localhost:8080/MainMenu
maxInactiveInterval=3600
ldap.enabled=false
hibernate.ddl.auto=none
extract.number=99
collectStats=false
OpenClinica.version=0.1
