import type { ThemeConfig } from "antd";

export type ThemeMode = "daylight" | "night";

function daylightTheme(): ThemeConfig {
  return {
    token: {
      colorPrimary: "#1f1f1f",
      colorPrimaryHover: "#3a3a3a",
      colorPrimaryActive: "#000000",
      colorSuccess: "#236b3a",
      colorWarning: "#7a5a00",
      colorError: "#8f1d1d",
      colorInfo: "#1a5a7a",
      colorBgContainer: "#ffffff",
      colorBgLayout: "#efefe9",
      colorBgElevated: "#ffffff",
      colorText: "#151515",
      colorTextSecondary: "#5f5f57",
      colorTextTertiary: "#8b8b83",
      colorBorder: "#d8d8d0",
      colorBorderSecondary: "#e5e5de",
      borderRadius: 4,
      borderRadiusLG: 6,
      fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      fontFamilyCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
      fontSize: 14,
      fontSizeHeading1: 24,
      fontSizeHeading2: 20,
      fontSizeHeading3: 18,
      fontSizeHeading4: 16,
      fontWeightStrong: 600,
      lineHeight: 1.5,
      lineHeightHeading1: 1.25,
      lineHeightHeading2: 1.3,
      lineHeightHeading3: 1.35,
      boxShadow: "none",
      boxShadowSecondary: "none",
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
      paddingContentVertical: 16,
      paddingContentHorizontal: 24,
      paddingLG: 24,
      paddingSM: 12,
      paddingXS: 8,
      marginLG: 24,
      marginSM: 12,
      marginXS: 8,
    },
    components: {
      Layout: {
        headerBg: "#1f1f1f",
        headerHeight: 52,
        bodyBg: "#efefe9",
        siderBg: "#ffffff",
        triggerBg: "#3a3a3a",
        triggerHeight: 40,
      },
      Menu: {
        itemBg: "#ffffff",
        itemBorderRadius: 4,
        itemColor: "#5f5f57",
        itemHoverColor: "#151515",
        itemHoverBg: "#f0f0eb",
        itemSelectedColor: "#151515",
        itemSelectedBg: "#e5e5de",
        itemActiveBg: "#d8d8d0",
        itemMarginInline: 4,
        itemHeight: 36,
        subMenuItemBg: "#ffffff",
        collapsedIconSize: 16,
      },
      Card: {
        paddingLG: 20,
        borderRadiusLG: 4,
        boxShadow: "none",
        boxShadowSecondary: "none",
      },
      Table: {
        headerBg: "#f7f7f4",
        headerBorderRadius: 4,
        rowHoverBg: "#f0f0eb",
        borderColor: "#e5e5de",
        headerColor: "#5f5f57",
        headerSortActiveBg: "#e5e5de",
        headerSortHoverBg: "#f0f0eb",
        rowSelectedBg: "#e5e5de",
        rowSelectedHoverBg: "#d8d8d0",
      },
      Button: {
        primaryShadow: "none",
        borderRadiusLG: 4,
        borderRadiusSM: 2,
        borderRadius: 4,
        fontWeight: 500,
        contentFontSize: 14,
        contentFontSizeLG: 15,
        contentFontSizeSM: 13,
        paddingBlock: 6,
        paddingInline: 16,
        paddingBlockLG: 8,
        paddingInlineLG: 20,
        defaultBorderColor: "#d8d8d0",
        defaultColor: "#151515",
        defaultHoverBorderColor: "#1f1f1f",
        defaultHoverColor: "#1f1f1f",
      },
      Tag: { borderRadius: 2, lineHeight: 1.6 },
      Modal: {
        borderRadiusLG: 6,
        boxShadowSecondary: "none",
        headerBg: "#ffffff",
        contentBg: "#ffffff",
        footerBg: "#f7f7f4",
      },
      Input: {
        borderRadius: 4, borderRadiusLG: 4,
        activeBorderColor: "#1f1f1f",
        hoverBorderColor: "#3a3a3a",
        activeShadow: "none",
        paddingBlock: 6,
      },
      Select: {
        borderRadius: 4, borderRadiusLG: 4,
        optionSelectedBg: "#e5e5de",
        optionActiveBg: "#f0f0eb",
      },
      Progress: { borderRadius: 2, defaultColor: "#1f1f1f", remainingColor: "#e5e5de" },
      Alert: { borderRadiusLG: 4 },
      Dropdown: { borderRadius: 4, boxShadowSecondary: "none" },
      Notification: { borderRadiusLG: 4 },
      Tabs: {
        inkBarColor: "#1f1f1f",
        itemSelectedColor: "#151515",
        itemHoverColor: "#1f1f1f",
        itemColor: "#5f5f57",
        titleFontSize: 14,
        titleFontSizeLG: 15,
      },
      Badge: { dotSize: 6, textFontSize: 11 },
      Statistic: { titleFontSize: 13, contentFontSize: 24 },
      Skeleton: { borderRadius: 4 },
      Divider: { verticalMarginInline: 8 },
      Spin: { dotSize: 24, dotSizeSM: 16 },
      Tooltip: { borderRadius: 4, colorBgSpotlight: "#1f1f1f" },
      Empty: { fontSize: 14 },
    },
  };
}

function nightTheme(): ThemeConfig {
  return {
    token: {
      colorPrimary: "#ecece5",
      colorPrimaryHover: "#d4d4ca",
      colorPrimaryActive: "#ffffff",
      colorSuccess: "#4caf7a",
      colorWarning: "#d4a854",
      colorError: "#e06050",
      colorInfo: "#5ab0d4",
      colorBgContainer: "#181816",
      colorBgLayout: "#161614",
      colorBgElevated: "#222220",
      colorText: "#ecece5",
      colorTextSecondary: "#b8b8ae",
      colorTextTertiary: "#7a7a72",
      colorBorder: "#383832",
      colorBorderSecondary: "#2a2a26",
      borderRadius: 4,
      borderRadiusLG: 6,
      fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      fontFamilyCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
      fontSize: 14,
      fontSizeHeading1: 24,
      fontSizeHeading2: 20,
      fontSizeHeading3: 18,
      fontSizeHeading4: 16,
      fontWeightStrong: 600,
      lineHeight: 1.5,
      lineHeightHeading1: 1.25,
      lineHeightHeading2: 1.3,
      lineHeightHeading3: 1.35,
      boxShadow: "none",
      boxShadowSecondary: "none",
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
      paddingContentVertical: 16,
      paddingContentHorizontal: 24,
      paddingLG: 24,
      paddingSM: 12,
      paddingXS: 8,
      marginLG: 24,
      marginSM: 12,
      marginXS: 8,
    },
    components: {
      Layout: {
        headerBg: "#181816",
        headerHeight: 52,
        bodyBg: "#161614",
        siderBg: "#181816",
        triggerBg: "#3a3a3a",
        triggerHeight: 40,
      },
      Menu: {
        itemBg: "#181816",
        itemBorderRadius: 4,
        itemColor: "#b8b8ae",
        itemHoverColor: "#ecece5",
        itemHoverBg: "#22221f",
        itemSelectedColor: "#ecece5",
        itemSelectedBg: "#2a2a26",
        itemActiveBg: "#383832",
        itemMarginInline: 4,
        itemHeight: 36,
        subMenuItemBg: "#181816",
        collapsedIconSize: 16,
      },
      Card: {
        paddingLG: 20,
        borderRadiusLG: 4,
        boxShadow: "none",
        boxShadowSecondary: "none",
      },
      Table: {
        headerBg: "#222220",
        headerBorderRadius: 4,
        rowHoverBg: "#22221f",
        borderColor: "#2a2a26",
        headerColor: "#b8b8ae",
        headerSortActiveBg: "#383832",
        headerSortHoverBg: "#22221f",
        rowSelectedBg: "#2a2a26",
        rowSelectedHoverBg: "#383832",
      },
      Button: {
        primaryShadow: "none",
        borderRadiusLG: 4, borderRadiusSM: 2, borderRadius: 4,
        fontWeight: 500,
        contentFontSize: 14, contentFontSizeLG: 15, contentFontSizeSM: 13,
        paddingBlock: 6, paddingInline: 16,
        paddingBlockLG: 8, paddingInlineLG: 20,
        defaultBorderColor: "#383832",
        defaultColor: "#ecece5",
        defaultHoverBorderColor: "#ecece5",
        defaultHoverColor: "#ffffff",
      },
      Tag: { borderRadius: 2, lineHeight: 1.6 },
      Modal: {
        borderRadiusLG: 6,
        boxShadowSecondary: "none",
        headerBg: "#222220",
        contentBg: "#181816",
        footerBg: "#222220",
      },
      Input: {
        borderRadius: 4, borderRadiusLG: 4,
        activeBorderColor: "#ecece5",
        hoverBorderColor: "#d4d4ca",
        activeShadow: "none",
        paddingBlock: 6,
      },
      Select: {
        borderRadius: 4, borderRadiusLG: 4,
        optionSelectedBg: "#2a2a26",
        optionActiveBg: "#22221f",
      },
      Progress: { borderRadius: 2, defaultColor: "#ecece5", remainingColor: "#2a2a26" },
      Alert: { borderRadiusLG: 4 },
      Dropdown: { borderRadius: 4, boxShadowSecondary: "none" },
      Notification: { borderRadiusLG: 4 },
      Tabs: {
        inkBarColor: "#ecece5",
        itemSelectedColor: "#ecece5",
        itemHoverColor: "#ffffff",
        itemColor: "#b8b8ae",
        titleFontSize: 14, titleFontSizeLG: 15,
      },
      Badge: { dotSize: 6, textFontSize: 11 },
      Statistic: { titleFontSize: 13, contentFontSize: 24 },
      Skeleton: { borderRadius: 4 },
      Divider: { verticalMarginInline: 8 },
      Spin: { dotSize: 24, dotSizeSM: 16 },
      Tooltip: { borderRadius: 4, colorBgSpotlight: "#ecece5" },
      Empty: { fontSize: 14 },
    },
  };
}

export function getTheme(mode: ThemeMode): ThemeConfig {
  return mode === "night" ? nightTheme() : daylightTheme();
}

export const defaultTheme: ThemeConfig = daylightTheme();
