import type { ThemeConfig } from "antd";

const theme: ThemeConfig = {
  token: {
    colorPrimary: "#1f1f1f",
    colorPrimaryHover: "#3a3a3a",
    colorPrimaryActive: "#000000",
    colorSuccess: "#236b3a",
    colorWarning: "#7a5a00",
    colorError: "#8f1d1d",
    colorInfo: "#1a5a7a",
    colorBgContainer: "#ffffff",
    colorBgLayout: "#efefe9",
    colorBgElevated: "#ffffff",
    colorText: "#151515",
    colorTextSecondary: "#5f5f57",
    colorTextTertiary: "#8b8b83",
    colorBorder: "#d8d8d0",
    colorBorderSecondary: "#e5e5de",
    borderRadius: 4,
    borderRadiusLG: 6,
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontFamilyCode: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    fontSize: 14,
    fontSizeHeading1: 24,
    fontSizeHeading2: 20,
    fontSizeHeading3: 18,
    fontSizeHeading4: 16,
    fontWeightStrong: 600,
    lineHeight: 1.5,
    lineHeightHeading1: 1.25,
    lineHeightHeading2: 1.3,
    lineHeightHeading3: 1.35,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    boxShadowSecondary: "0 2px 8px rgba(0,0,0,0.06)",
    controlHeight: 36,
    controlHeightLG: 44,
    controlHeightSM: 28,
    paddingContentVertical: 16,
    paddingContentHorizontal: 24,
    paddingLG: 24,
    paddingSM: 12,
    paddingXS: 8,
    marginLG: 24,
    marginSM: 12,
    marginXS: 8,
  },
  components: {
    Layout: {
      headerBg: "#1f1f1f",
      headerHeight: 52,
      bodyBg: "#efefe9",
      siderBg: "#ffffff",
      triggerBg: "#3a3a3a",
      triggerHeight: 40,
    },
    Menu: {
      itemBg: "transparent",
      itemBorderRadius: 4,
      itemColor: "#5f5f57",
      itemHoverColor: "#151515",
      itemHoverBg: "rgba(0,0,0,0.04)",
      itemSelectedColor: "#151515",
      itemSelectedBg: "rgba(0,0,0,0.08)",
      itemActiveBg: "rgba(0,0,0,0.10)",
      itemMarginInline: 4,
      itemHeight: 36,
      subMenuItemBg: "transparent",
      collapsedIconSize: 16,
    },
    Card: {
      paddingLG: 20,
      borderRadiusLG: 4,
      boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
      boxShadowSecondary: "0 2px 8px rgba(0,0,0,0.06)",
    },
    Table: {
      headerBg: "#f7f7f4",
      headerBorderRadius: 4,
      rowHoverBg: "rgba(0,0,0,0.02)",
      borderColor: "#e5e5de",
      headerColor: "#5f5f57",
      headerSortActiveBg: "rgba(0,0,0,0.03)",
      headerSortHoverBg: "rgba(0,0,0,0.02)",
      rowSelectedBg: "rgba(0,0,0,0.04)",
      rowSelectedHoverBg: "rgba(0,0,0,0.06)",
    },
    Button: {
      primaryShadow: "none",
      borderRadiusLG: 4,
      borderRadiusSM: 2,
      borderRadius: 4,
      fontWeight: 500,
      contentFontSize: 14,
      contentFontSizeLG: 15,
      contentFontSizeSM: 13,
      paddingBlock: 6,
      paddingInline: 16,
      paddingBlockLG: 8,
      paddingInlineLG: 20,
      defaultBorderColor: "#d8d8d0",
      defaultColor: "#151515",
      defaultHoverBorderColor: "#1f1f1f",
      defaultHoverColor: "#1f1f1f",
    },
    Tag: {
      borderRadius: 2,
      lineHeight: 1.6,
    },
    Modal: {
      borderRadiusLG: 6,
      boxShadowSecondary: "0 2px 8px rgba(0,0,0,0.06)",
      headerBg: "#ffffff",
      contentBg: "#ffffff",
      footerBg: "#f7f7f4",
    },
    Input: {
      borderRadius: 4,
      borderRadiusLG: 4,
      activeBorderColor: "#1f1f1f",
      hoverBorderColor: "#3a3a3a",
      activeShadow: "0 0 0 2px rgba(0,0,0,0.06)",
      paddingBlock: 6,
    },
    Select: {
      borderRadius: 4,
      borderRadiusLG: 4,
      optionSelectedBg: "rgba(0,0,0,0.08)",
      optionActiveBg: "rgba(0,0,0,0.04)",
    },
    Progress: {
      borderRadius: 2,
      defaultColor: "#1f1f1f",
      remainingColor: "#e5e5de",
    },
    Alert: {
      borderRadiusLG: 4,
    },
    Dropdown: {
      borderRadius: 4,
      boxShadowSecondary: "0 2px 8px rgba(0,0,0,0.06)",
    },
    Notification: {
      borderRadiusLG: 4,
    },
    Tabs: {
      inkBarColor: "#1f1f1f",
      itemSelectedColor: "#151515",
      itemHoverColor: "#1f1f1f",
      itemColor: "#5f5f57",
      titleFontSize: 14,
      titleFontSizeLG: 15,
    },
    Badge: {
      dotSize: 6,
      textFontSize: 11,
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 24,
    },
    Skeleton: {
      borderRadius: 4,
    },
    Divider: {
      verticalMarginInline: 8,
    },
    Spin: {
      dotSize: 24,
      dotSizeSM: 16,
    },
    Tooltip: {
      borderRadius: 4,
      colorBgSpotlight: "#1f1f1f",
    },
    Empty: {
      fontSize: 14,
    },
  },
};

export default theme;