package org.researchedc.module.randomization.enums;

public enum AuditAction {
    SCHEME_CREATED,
    SCHEME_UPDATED,
    SCHEME_ACTIVATED,
    SCHEME_PAUSED,
    SCHEME_CLOSED,
    ARM_CREATED,
    ARM_UPDATED,
    STRATUM_CREATED,
    STRATUM_UPDATED,
    SUBJECT_ASSIGNED,
    ASSIGNMENT_REVOKED,
    UNBLINDING_REQUESTED,
    UNBLINDING_APPROVED,
    UNBLINDING_REJECTED
}
