#!/bin/bash
# =============================================================================
# ResearchEDC Docker Entrypoint
#
# Generates datainfo.properties from RESEARCHEDC_DB_* environment variables
# at runtime, then launches Tomcat.
# =============================================================================
set -e

# ---- Configuration ----
# Determine webapp name from context path
# Deployed as ROOT.war -> context path is "" -> WEBAPP is "ROOT"
# CoreResources.resolveWebapp uses the last path segment of the real path
# For ROOT.war, it resolves to "" which makes ${WEBAPP.lower} = "root"
# We override by setting it explicitly via env
WEBAPP_NAME="${RESEARCHEDC_WEBAPP_NAME:-root}"

# Config directory: CoreResources reads from $catalina.home/$WEBAPP.lower.config/
# We'll also put a copy in the classpath-accessible location
CATALINA_HOME="${CATALINA_HOME:-/usr/local/tomcat}"
CONFIG_DIR="${CATALINA_HOME}/${WEBAPP_NAME}.config"
DATA_DIR="${RESEARCHEDC_FILE_PATH:-/opt/researchedc/data}"
LOG_DIR="${RESEARCHEDC_LOG_DIR:-/opt/researchedc/logs}"

mkdir -p "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}"

# ---- Generate datainfo.properties ----
cat > "${CONFIG_DIR}/datainfo.properties" << EOF
# =============================================================================
# ResearchEDC Database Configuration
# Auto-generated by Docker entrypoint — DO NOT EDIT
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# Database — no default password: must be set via environment
dbType=${RESEARCHEDC_DB_TYPE:-postgres}
dbHost=${RESEARCHEDC_DB_HOST:-postgres}
dbPort=${RESEARCHEDC_DB_PORT:-5432}
db=${RESEARCHEDC_DB_NAME:?RESEARCHEDC_DB_NAME is required}
dbUser=${RESEARCHEDC_DB_USER:?RESEARCHEDC_DB_USER is required}
dbPass=${RESEARCHEDC_DB_PASS:?RESEARCHEDC_DB_PASS is required}

# File paths
filePath=${DATA_DIR}/

# Logging
log.dir=${LOG_DIR}
logLocation=local
logLevel=${RESEARCHEDC_LOG_LEVEL:-info}

# System URL
sysURL=${RESEARCHEDC_SYS_URL:?RESEARCHEDC_SYS_URL is required}

# Admin email — must be configured; no default
adminEmail=${RESEARCHEDC_ADMIN_EMAIL:?RESEARCHEDC_ADMIN_EMAIL is required}

# User account notification (email or screen)
userAccountNotification=${RESEARCHEDC_USER_ACCOUNT_NOTIFICATION:-email}

# Session timeout (seconds)
maxInactiveInterval=${RESEARCHEDC_MAX_INACTIVE_INTERVAL:-3600}

# Mail configuration
mailHost=${RESEARCHEDC_MAIL_HOST:-mailhog}
mailPort=${RESEARCHEDC_MAIL_PORT:-1025}
mailProtocol=${RESEARCHEDC_MAIL_PROTOCOL:-smtp}
mailUsername=${RESEARCHEDC_MAIL_USER:-}
mailPassword=${RESEARCHEDC_MAIL_PASS:-}
mailSmtpAuth=${RESEARCHEDC_MAIL_AUTH:-false}
mailSmtpStarttls.enable=${RESEARCHEDC_MAIL_STARTTLS:-false}
mailSmtpsAuth=false
mailSmtpsStarttls.enable=false
mailSmtpConnectionTimeout=${RESEARCHEDC_MAIL_TIMEOUT:-100}
mailErrorMsg=${RESEARCHEDC_ADMIN_EMAIL:?RESEARCHEDC_ADMIN_EMAIL is required}

# LDAP configuration
ldap.enabled=${RESEARCHEDC_LDAP_ENABLED:-false}
ldap.host=${RESEARCHEDC_LDAP_HOST:-ldap://localhost:389}
ldap.userDn=${RESEARCHEDC_LDAP_USER_DN:-}
ldap.password=${RESEARCHEDC_LDAP_PASS:-}
ldap.loginQuery=${RESEARCHEDC_LDAP_LOGIN_QUERY:-(sAMAccountName={0})}
ldap.passwordRecoveryURL=${RESEARCHEDC_LDAP_PWD_RECOVERY_URL:-}
ldap.userSearch.baseDn=${RESEARCHEDC_LDAP_BASE_DN:-}
ldap.userSearch.query=${RESEARCHEDC_LDAP_SEARCH_QUERY:-}
ldap.userData.distinguishedName=distinguishedName
ldap.userData.username=sAMAccountName
ldap.userData.firstName=givenName
ldap.userData.lastName=sn
ldap.userData.email=mail
ldap.userData.organization=department

# Quartz Scheduler
org.quartz.jobStore.misfireThreshold=${RESEARCHEDC_QUARTZ_MISFIRE_THRESHOLD:-18000000}
org.quartz.threadPool.threadCount=${RESEARCHEDC_QUARTZ_THREAD_COUNT:-1}
org.quartz.threadPool.threadPriority=${RESEARCHEDC_QUARTZ_THREAD_PRIORITY:-5}

# Hibernate DDL auto (none | validate | update | create | create-drop)
# Default 'none' for production; set 'validate' to check schema compatibility
hibernate.ddl.auto=${RESEARCHEDC_HIBERNATE_DDL_AUTO:-none}

# Other
extract.number=${RESEARCHEDC_EXTRACT_PAGE_SIZE:-99}
collectStats=${RESEARCHEDC_COLLECT_STATS:-false}
designerURL=${RESEARCHEDC_DESIGNER_URL:-https://designer13.openclinica.com/}
OpenClinica.version=3.18-SNAPSHOT
EOF

# Security: only write credentials to CONFIG_DIR, not to WEBAPP_CLASSES.
# Use spring.config.additional-location if classpath access is needed.

echo "[entrypoint] Generated datainfo.properties:"
echo "  DB:     ${RESEARCHEDC_DB_TYPE}://${RESEARCHEDC_DB_HOST}:${RESEARCHEDC_DB_PORT}/${RESEARCHEDC_DB_NAME}"
echo "  Data:   ${DATA_DIR}"
echo "  Logs:   ${LOG_DIR}"
echo "  Config: ${CONFIG_DIR}"
echo "  Mail:   ${RESEARCHEDC_MAIL_HOST}:${RESEARCHEDC_MAIL_PORT}"
echo ""

# Execute the CMD (catalina.sh run)
exec "$@"
