#!/bin/bash
# =============================================================================
# OpenClinica Docker Entrypoint
#
# Generates datainfo.properties from OC_DB_* environment variables at runtime,
# then launches Tomcat.
# =============================================================================
set -e

# ---- Configuration ----
# Determine webapp name from context path
# Deployed as ROOT.war → context path is "" → WEBAPP is "ROOT"
# CoreResources.resolveWebapp uses the last path segment of the real path
# For ROOT.war, it resolves to "" which makes ${WEBAPP.lower} = "root"
# We override by setting it explicitly via env
WEBAPP_NAME="${OC_WEBAPP_NAME:-root}"

# Config directory: CoreResources reads from $catalina.home/$WEBAPP.lower.config/
# We'll also put a copy in the classpath-accessible location
CATALINA_HOME="${CATALINA_HOME:-/usr/local/tomcat}"
CONFIG_DIR="${CATALINA_HOME}/${WEBAPP_NAME}.config"
DATA_DIR="${OC_FILE_PATH:-/opt/openclinica/data}"
LOG_DIR="${OC_LOG_DIR:-/opt/openclinica/logs}"

mkdir -p "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}"

# ---- Generate datainfo.properties ----
cat > "${CONFIG_DIR}/datainfo.properties" << EOF
# =============================================================================
# OpenClinica Database Configuration
# Auto-generated by Docker entrypoint — DO NOT EDIT
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# Database
dbType=${OC_DB_TYPE:-postgres}
dbHost=${OC_DB_HOST:-postgres}
dbPort=${OC_DB_PORT:-5432}
db=${OC_DB_NAME:-openclinica}
dbUser=${OC_DB_USER:-openclinica}
dbPass=${OC_DB_PASS:-openclinica}

# File paths
filePath=${DATA_DIR}/

# Logging
log.dir=${LOG_DIR}
logLocation=local
logLevel=${OC_LOG_LEVEL:-info}

# System URL
sysURL=${OC_SYS_URL:-http://localhost:8080/MainMenu}

# Admin email
adminEmail=${OC_ADMIN_EMAIL:-admin@example.com}

# User account notification (email or screen)
userAccountNotification=${OC_USER_ACCOUNT_NOTIFICATION:-email}

# Session timeout (seconds)
maxInactiveInterval=${OC_MAX_INACTIVE_INTERVAL:-3600}

# Mail configuration
mailHost=${OC_MAIL_HOST:-mailhog}
mailPort=${OC_MAIL_PORT:-1025}
mailProtocol=${OC_MAIL_PROTOCOL:-smtp}
mailUsername=${OC_MAIL_USER:-}
mailPassword=${OC_MAIL_PASS:-}
mailSmtpAuth=${OC_MAIL_AUTH:-false}
mailSmtpStarttls.enable=${OC_MAIL_STARTTLS:-false}
mailSmtpsAuth=false
mailSmtpsStarttls.enable=false
mailSmtpConnectionTimeout=${OC_MAIL_TIMEOUT:-100}
mailErrorMsg=${OC_ADMIN_EMAIL:-admin@example.com}

# LDAP configuration
ldap.enabled=${OC_LDAP_ENABLED:-false}
ldap.host=${OC_LDAP_HOST:-ldap://localhost:389}
ldap.userDn=${OC_LDAP_USER_DN:-}
ldap.password=${OC_LDAP_PASS:-}
ldap.loginQuery=${OC_LDAP_LOGIN_QUERY:-(sAMAccountName={0})}
ldap.passwordRecoveryURL=${OC_LDAP_PWD_RECOVERY_URL:-}
ldap.userSearch.baseDn=${OC_LDAP_BASE_DN:-}
ldap.userSearch.query=${OC_LDAP_SEARCH_QUERY:-}
ldap.userData.distinguishedName=distinguishedName
ldap.userData.username=sAMAccountName
ldap.userData.firstName=givenName
ldap.userData.lastName=sn
ldap.userData.email=mail
ldap.userData.organization=department

# Quartz Scheduler
org.quartz.jobStore.misfireThreshold=${OC_QUARTZ_MISFIRE_THRESHOLD:-18000000}
org.quartz.threadPool.threadCount=${OC_QUARTZ_THREAD_COUNT:-1}
org.quartz.threadPool.threadPriority=${OC_QUARTZ_THREAD_PRIORITY:-5}

# Hibernate DDL auto (none | validate | update | create | create-drop)
# Default 'none' for production; set 'validate' to check schema compatibility
hibernate.ddl.auto=${OC_HIBERNATE_DDL_AUTO:-none}

# Other
extract.number=${OC_EXTRACT_PAGE_SIZE:-99}
collectStats=${OC_COLLECT_STATS:-false}
designerURL=${OC_DESIGNER_URL:-https://designer13.openclinica.com/}
OpenClinica.version=3.18-SNAPSHOT
EOF

# Also place a copy in the classpath for Spring context loading
# (CoreResources also looks for classpath:datainfo.properties)
cp "${CONFIG_DIR}/datainfo.properties" "${CATALINA_HOME}/webapps/ROOT/WEB-INF/classes/datainfo.properties" 2>/dev/null || true

echo "[entrypoint] Generated datainfo.properties:"
echo "  DB:     ${OC_DB_TYPE}://${OC_DB_HOST}:${OC_DB_PORT}/${OC_DB_NAME}"
echo "  Data:   ${DATA_DIR}"
echo "  Logs:   ${LOG_DIR}"
echo "  Config: ${CONFIG_DIR}"
echo "  Mail:   ${OC_MAIL_HOST}:${OC_MAIL_PORT}"
echo ""

# Execute the CMD (catalina.sh run)
exec "$@"
