#!/usr/bin/env bash
set -euo pipefail

echo "=== Import rollback PostgreSQL validation ==="

required_env=(
  IMPORT_ROLLBACK_PGHOST
  IMPORT_ROLLBACK_PGPORT
  IMPORT_ROLLBACK_PGDATABASE
  IMPORT_ROLLBACK_PGUSER
  IMPORT_ROLLBACK_PGPASSWORD
)

for name in "${required_env[@]}"; do
  if [ -z "${!name:-}" ]; then
    echo "SKIP: ${name} is not set. This check only runs against an explicit disposable PostgreSQL database."
    exit 0
  fi
done

export PGPASSWORD="${IMPORT_ROLLBACK_PGPASSWORD}"

psql_args=(
  -v ON_ERROR_STOP=1
  -h "${IMPORT_ROLLBACK_PGHOST}"
  -p "${IMPORT_ROLLBACK_PGPORT}"
  -U "${IMPORT_ROLLBACK_PGUSER}"
  -d "${IMPORT_ROLLBACK_PGDATABASE}"
)

psql "${psql_args[@]}" <<'SQL'
\echo 'Preparing isolated import rollback probe table'

CREATE TEMP TABLE import_rollback_probe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marker TEXT NOT NULL
);

\echo 'Verifying failed import-style transaction leaves no partial writes'

DO $$
BEGIN
  BEGIN
    INSERT INTO import_rollback_probe(marker) VALUES ('before-failure');
    RAISE EXCEPTION 'simulate import commit failure after data mutation';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Observed expected simulated import failure: %', SQLERRM;
  END;
END $$;

DO $$
DECLARE partial_writes integer;
BEGIN
  SELECT count(*) INTO partial_writes FROM import_rollback_probe;
  IF partial_writes <> 0 THEN
    RAISE EXCEPTION 'Failed import transaction left % partial write(s)', partial_writes;
  END IF;
END $$;
SQL

echo "Import rollback PostgreSQL validation passed."
