global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'openclinica'
    metrics_path: '/OpenClinica/actuator/prometheus'
    static_configs:
      - targets: ['web:8080']
        labels:
          application: 'OpenClinica'
