package org.researchedc.dao.spi;

import org.researchedc.bean.core.AuditableEntityBean;
import org.researchedc.bean.core.EntityBean;
import org.researchedc.bean.core.Status;
import org.researchedc.bean.managestudy.StudyBean;
import org.researchedc.bean.managestudy.StudyEventBean;
import org.researchedc.bean.managestudy.StudySubjectBean;
import org.researchedc.bean.submit.CRFVersionBean;
import org.researchedc.bean.submit.EventCRFBean;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;

public interface EventCRFDao {
    EntityBean findByPK(int ID);
    EntityBean create(EntityBean eb);
    EntityBean update(EntityBean eb);
    Collection findAll();
    Collection findAll(String strOrderByColumn, boolean blnAscendingSort, String strSearchPhrase);
    Collection findAllByPermission(Object objCurrentUser, int intActionType, String strOrderByColumn, boolean blnAscendingSort, String strSearchPhrase);
    Collection findAllByPermission(Object objCurrentUser, int intActionType);
    Object getEntityFromHashMap(HashMap hm);
    ArrayList findAllByStudyEvent(StudyEventBean studyEvent);
    ArrayList findAllByStudyEventAndStatus(StudyEventBean studyEvent, Status status);
    ArrayList<EventCRFBean> findAllByStudySubject(int studySubjectId);
    ArrayList findAllByStudyEventAndCrfOrCrfVersionOid(StudyEventBean studyEvent, String crfVersionOrCrfOID);
    ArrayList<EventCRFBean> findAllByStudyEventInParticipantForm(StudyEventBean studyEvent, int sed_Id, int studyId);
    ArrayList<EventCRFBean> findAllByStudyEventDefinition(int sed_Id, int studyId);
    ArrayList findAllByCRF(int crfId);
    ArrayList findAllByCRFVersion(int versionId);
    ArrayList findAllStudySubjectByCRFVersion(int versionId);
    ArrayList findUndeletedWithStudySubjectsByCRFVersion(int versionId);
    ArrayList findByEventSubjectVersion(StudyEventBean studyEvent, StudySubjectBean studySubject, CRFVersionBean crfVersion);
    EventCRFBean findByEventCrfVersion(StudyEventBean studyEvent, CRFVersionBean crfVersion);
    ArrayList<EventCRFBean> findByCrfVersion(CRFVersionBean crfVersion);
    void delete(int eventCRFId);
    void setSDVStatus(boolean sdvStatus, int userId, int eventCRFId);
    void markComplete(EventCRFBean ecb, boolean ide);
    void updateCRFVersionID(int event_crf_id, int crf_version_id, int user_id);
    void updateCRFVersionID(int event_crf_id, int crf_version_id, int user_id, java.sql.Connection con);
    ArrayList findByEventSubjectCRFid(StudyEventBean studyEvent, StudySubjectBean studySubject, CRFVersionBean crfVersion);
    EventCRFBean findByEventCrfID(StudyEventBean studyEvent, CRFVersionBean crfVersion);
    Map<Integer, SortedSet<EventCRFBean>> buildEventCrfListByStudyEvent(Integer studySubjectId);
    Set<Integer> buildNonEmptyEventCrfIds(Integer studySubjectId);
    List<EventCRFBean> findAllCRFMigrationReportList(CRFVersionBean sourceCrfVersionBean, CRFVersionBean targetCrfVersionBean, ArrayList<String> studyEventDefnlist, ArrayList<String> sitelist);
    Integer countEventCRFsByEventNameSubjectLabel(String eventName, String subjectLabel);
    AuditableEntityBean findByPKAndStudy(int id, StudyBean study);
    boolean isQuerySuccessful();
    Integer countEventCRFsByStudySubject(int studySubjectId, int studyId, int parentStudyId);
    ArrayList getEventCRFsByStudySubjectCompleteOrLocked(int studySubjectId);
    ArrayList getEventCRFsByStudySubjectLimit(int studySubjectId, int studyId, int parentStudyId, int limit, int offset);
    ArrayList getEventCRFsByStudySubject(int studySubjectId, int studyId, int parentStudyId);    ArrayList getEventCRFsByStudySubjectLabelLimit(String label, int studyId, int parentStudyId, int limit, int offset);
    Integer countEventCRFsByStudySubjectLabel(String label, int studyId, int parentStudyId);
}
