package org.researchedc.domain.datamap;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.researchedc.domain.DataMapDomainObject;
import org.researchedc.domain.user.UserAccount;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DiscrepancyNote generated by hbm2java
 */
@Entity
@Table(name = "discrepancy_note")
@GenericGenerator(name = "id-generator", strategy = "native", parameters = { @Parameter(name = "sequence", value = "discrepancy_note_discrepancy_note_id_seq") })
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class DiscrepancyNote  extends DataMapDomainObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int discrepancyNoteId;
	private UserAccount userAccountByOwnerId;
	private DiscrepancyNoteType discrepancyNoteType;
	private UserAccount userAccount;
	private Study study;
	private ResolutionStatus resolutionStatus;
	private String description;
	private String detailedNotes;
	private Date dateCreated;
	private Integer parentDnId;
	private String entityType;
	private DiscrepancyNote parentDiscrepancyNote;

	public DiscrepancyNote() {
	}

	public DiscrepancyNote(int discrepancyNoteId) {
		this.discrepancyNoteId = discrepancyNoteId;
	}

	public DiscrepancyNote(int discrepancyNoteId,
			UserAccount userAccountByOwnerId,
			DiscrepancyNoteType discrepancyNoteType,
			UserAccount userAccount, Study study,
			ResolutionStatus resolutionStatus, String description,
			String detailedNotes, Date dateCreated, Integer parentDnId,
			String entityType) {
		this.discrepancyNoteId = discrepancyNoteId;
		this.userAccountByOwnerId = userAccountByOwnerId;
		this.discrepancyNoteType = discrepancyNoteType;
		this.userAccount = userAccount;
		this.study = study;
		this.resolutionStatus = resolutionStatus;
		this.description = description;
		this.detailedNotes = detailedNotes;
		this.dateCreated = dateCreated;
		this.parentDnId = parentDnId;
		this.entityType = entityType;
	}

	@Id
	@Column(name = "discrepancy_note_id", unique = true, nullable = false)
	@GeneratedValue(generator = "id-generator")
	public int getDiscrepancyNoteId() {
		return this.discrepancyNoteId;
	}

	public void setDiscrepancyNoteId(int discrepancyNoteId) {
		this.discrepancyNoteId = discrepancyNoteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id")
	public UserAccount getUserAccountByOwnerId() {
		return this.userAccountByOwnerId;
	}

	public void setUserAccountByOwnerId(UserAccount userAccountByOwnerId) {
		this.userAccountByOwnerId = userAccountByOwnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discrepancy_note_type_id" )
	public DiscrepancyNoteType getDiscrepancyNoteType() {
		return this.discrepancyNoteType;
	}

	public void setDiscrepancyNoteType(DiscrepancyNoteType discrepancyNoteType) {
		this.discrepancyNoteType = discrepancyNoteType;
	}

	@ManyToOne(fetch = FetchType.LAZY )
	@JoinColumn(name = "assigned_user_id")
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(
			UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "study_id")
	public Study getStudy() {
		return this.study;
	}

	public void setStudy(Study study) {
		this.study = study;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resolution_status_id")
	public ResolutionStatus getResolutionStatus() {
		return this.resolutionStatus;
	}

	public void setResolutionStatus(ResolutionStatus resolutionStatus) {
		this.resolutionStatus = resolutionStatus;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "detailed_notes", length = 1000)
	public String getDetailedNotes() {
		return this.detailedNotes;
	}

	public void setDetailedNotes(String detailedNotes) {
		this.detailedNotes = detailedNotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 8)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
/*
	@Column(name = "parent_dn_id")
	public Integer getParentDnId() {
		return this.parentDnId;
	}

	public void setParentDnId(Integer parentDnId) {
		this.parentDnId = parentDnId;
	}
*/
	
	
	@Column(name = "entity_type", length = 30)
	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_dn_id")
	public DiscrepancyNote getParentDiscrepancyNote(){
		return this.parentDiscrepancyNote;
	}
	
	public void setParentDiscrepancyNote(DiscrepancyNote parentDiscrepancyNote){
		this.parentDiscrepancyNote = parentDiscrepancyNote;
	}
}
