package org.akaza.openclinica.domain.datamap;

//default package
//Generated Jul 31, 2013 2:03:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import org.akaza.openclinica.domain.DataMapDomainObject;

/**
* GroupClassTypes generated by hbm2java
*/
@Entity
@Table(name = "group_class_types")
public class GroupClassTypes  extends DataMapDomainObject {

	private int groupClassTypeId;
	private String name;
	private String description;
	private List<StudyGroupClass> studyGroupClasses ;

	public GroupClassTypes() {
	}

	public GroupClassTypes(int groupClassTypeId) {
		this.groupClassTypeId = groupClassTypeId;
	}

	public GroupClassTypes(int groupClassTypeId, String name,
			String description, List<StudyGroupClass>  studyGroupClasses) {
		this.groupClassTypeId = groupClassTypeId;
		this.name = name;
		this.description = description;
		this.studyGroupClasses = studyGroupClasses;
	}

	@Id
	@Column(name = "group_class_type_id", unique = true, nullable = false)
	public int getGroupClassTypeId() {
		return this.groupClassTypeId;
	}

	public void setGroupClassTypeId(int groupClassTypeId) {
		this.groupClassTypeId = groupClassTypeId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupClassTypes")
	public List<StudyGroupClass> getStudyGroupClasses() {
		return this.studyGroupClasses;
	}

	public void setStudyGroupClasses(List<StudyGroupClass> studyGroupClasses) {
		this.studyGroupClasses = studyGroupClasses;
	}

}
